name: Demo manual workflow

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Mensaje a imprimir por consola'
        required: true
        default: 'Hola desde GitHub Actions'

jobs:
  imprimir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "${{ github.event.inputs.mensaje }}"
